"""AI Decision Logger core engine.

Manages recording suggestions generated by AI models and mapping subsequent user/system 
actions (e.g. modify, reject, revert) to log deferred suggestion outcomes.
"""

from datetime import datetime, timezone
from vexiq.models import AIDecision, DecisionOutcome
from vexiq.db import (
    insert_decision,
    get_decision_by_id,
    update_decision_outcome,
    list_recent_decisions,
    find_recent_duplicate_decision,
)


class DecisionLogger:
    """Service layer class for handling AIDecision persistence, retrieval, deduplication

    safeguards, and outcomes updates.

    CRITICAL IMMUTABILITY RULE:
    Logged AI decisions are audit-style records and are mostly write-once.
    All properties supplied during creation (including provider, model_id, task_type,
    suggestion_summary, user_action, and suggestion_hash) are strictly immutable.
    Only the deferred outcome state (such as `outcome` and `outcome_recorded_at`) can
    be updated.
    """

    def __init__(self, db_path: str):
        """Initializes DecisionLogger with a reference to the active SQLite database path."""
        self.db_path = db_path

    async def create_decision(self, decision: AIDecision) -> AIDecision:
        """Evaluates deduplication safeguards and persists the decision record.

        Args:
            decision: Fully constructed AIDecision model.
        """
        # Deduplication safeguard: look for matching decision in the last 10 seconds
        duplicate = await find_recent_duplicate_decision(
            self.db_path,
            suggestion_hash=decision.suggestion_hash,
            session_id=decision.session_id,
            provider=decision.provider,
            model_id=decision.model_id,
            user_action=decision.user_action,
            window_seconds=10,
            reference_time=decision.timestamp,
        )
        if duplicate:
            return duplicate

        await insert_decision(self.db_path, decision)
        return decision

    async def get_decision(self, decision_id: str) -> AIDecision | None:
        """Retrieves a logged decision by its UUID decision_id.

        Args:
            decision_id: The UUID decision identifier.
        """
        return await get_decision_by_id(self.db_path, decision_id)

    async def update_outcome(
        self,
        decision_id: str,
        outcome: DecisionOutcome,
        outcome_recorded_at: datetime | None = None,
    ) -> AIDecision | None:
        """Updates outcome status and recording timestamps on an existing decision.

        CRITICAL IMMUTABILITY RULE:
        Only deferred outcome fields (`outcome` and `outcome_recorded_at`) can be updated.
        All other fields are write-once and strictly immutable to maintain log integrity.

        Args:
            decision_id: The UUID decision identifier.
            outcome: New outcome designation.
            outcome_recorded_at: Custom timestamp; defaults to current UTC time.
        """
        if outcome_recorded_at is None:
            outcome_recorded_at = datetime.now(timezone.utc)
        return await update_decision_outcome(
            self.db_path, decision_id, outcome, outcome_recorded_at
        )

    async def list_recent_decisions(self, limit: int = 20) -> list[AIDecision]:
        """Lists recently logged decision occurrences.

        Args:
            limit: Maximum count of returned records.
        """
        return await list_recent_decisions(self.db_path, limit)
